Temperature and repetier FW updates
KDE/atcore pull request #11
Opened 2016-09-27 01:11 UTC by patrickelectric

2016-09-27 14:52 UTC, sithlord48 requested changes

2016-09-27 14:52 UTC, sithlord48 commented on working.diff
> +diff --git a/src/ifirmware.h b/src/ifirmware.h
What is this diff file?

2016-09-27 14:52 UTC, sithlord48 commented on testclient/mainwindow.ui
> +             <widget class="QLabel" name="bedTempLB">
These Gui changes are not connected to anything can we do this on a commit that also contains logic to make them function.

2016-09-27 14:52 UTC, sithlord48 commented on src/plugins/repetierplugin.cpp
> +    qCDebug(REPETIER_PLUGIN) << "Starting.. " << name();
this just sounds weird coming from within the plugin like this maybe change the message to 
qCDebug(REPETIER_PLUGIN) << name() << " plugin loaded" 
 or something similar to that.

2016-09-28 17:05 UTC, patrickelectric commented on working.diff
> +diff --git a/src/ifirmware.h b/src/ifirmware.h
An error

2016-09-28 17:07 UTC, patrickelectric commented on src/plugins/repetierplugin.cpp
> +    qCDebug(REPETIER_PLUGIN) << "Starting.. " << name();
Done

2016-09-28 18:49 UTC, sithlord48 approved these changes

2016-09-28 18:55 UTC, merged