Being Work for state tracking
KDE/atcore pull request #13
Opened 2016-09-28 17:23 UTC by sithlord48

Initial work to track the state of the printer. A few imediate beinfits have already been reaslized you can connect and disconnect now successfully multipal times durring runtime. And simple Pause feature is working.

2016-09-28 20:41 UTC, patrickelectric requested changes

2016-09-28 20:41 UTC, patrickelectric commented on testclient/mainwindow.cpp
> +        fileName = QFileDialog::getOpenFileName(this, tr("Select A file to print"), QDir::homePath(), "*.gcode");
a file

2016-09-28 20:41 UTC, patrickelectric commented on testclient/mainwindow.cpp
> +        ui->printPB->setText(tr("Resume Print"));
Printer

2016-09-28 20:41 UTC, patrickelectric commented on testclient/mainwindow.cpp
> +        ui->printPB->setText(tr("Pause Print"));
Printer

2016-09-28 20:41 UTC, patrickelectric commented on testclient/mainwindow.ui
>     <rect>
ui changes  in different commit please

2016-09-28 21:38 UTC, sithlord48 commented on testclient/mainwindow.cpp
> +        ui->printPB->setText(tr("Resume Print"));
Its Print as in the current print job running.

2016-09-28 21:39 UTC, sithlord48 commented on testclient/mainwindow.ui
>     <rect>
Just the changes to the ui file in a seperate commit?

2016-09-29 01:06 UTC, sithlord48 commented on testclient/mainwindow.cpp
> +        fileName = QFileDialog::getOpenFileName(this, tr("Select A file to print"), QDir::homePath(), "*.gcode");
:heavy_check_mark:  done

2016-09-29 01:06 UTC, sithlord48 commented on testclient/mainwindow.ui
>     <rect>
:heavy_check_mark:  done

2016-09-29 01:08 UTC, patrickelectric approved these changes
Can be merged

2016-09-29 01:09 UTC, merged