Process Emergency Stop
KDE/atcore pull request #17
Opened 2016-10-01 14:46 UTC by sithlord48

Emergency Stop is now no the testGUI and when pressed it will either send M112 directly or if the printer is in a busy state it will set the printers state to "STOP" and atcore will do the rest.

2016-10-01 20:30 UTC, patrickelectric requested changes

2016-10-01 20:30 UTC, patrickelectric commented on testclient/mainwindow.cpp
> +        core->serial()->pushCommand(QString("M112").toLocal8Bit());
Here, the command need to be sent to atcore.

2016-10-01 20:30 UTC, patrickelectric commented on testclient/mainwindow.cpp
> +    if (core->state() == BUSY) {
It's better to send only the stop command to the printer. Don't have problem if you send more than one.

2016-10-01 20:30 UTC, patrickelectric commented on src/atcore.cpp
> +            QString stopString("M112");
use gcode namespace

2016-10-01 20:30 UTC, patrickelectric commented on testclient/mainwindow.cpp
> +        core->serial()->pushCommand(QString("M112").toLocal8Bit());
use gcode namespace

2016-10-02 02:56 UTC, sithlord48 commented on src/atcore.cpp
> +            QString stopString("M112");
:heavy_check_mark:

2016-10-02 02:56 UTC, sithlord48 commented on testclient/mainwindow.cpp
> +        core->serial()->pushCommand(QString("M112").toLocal8Bit());
:heavy_check_mark:

2016-10-02 13:38 UTC, patrickelectric requested changes
Use setState and state functions

2016-10-02 13:56 UTC, patrickelectric requested changes
Change from if else to switch case

2016-10-02 14:00 UTC, patrickelectric requested changes
Change from d->serial to serial()

2016-10-02 22:19 UTC, patrickelectric approved these changes

2016-10-02 22:29 UTC, closed without merging