mainwindow: Solve connect bug
KDE/atcore pull request #20
Opened 2016-10-02 23:46 UTC by patrickelectric

set IDLE state when connected

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

2016-10-03 21:18 UTC, sithlord48 requested changes

2016-10-03 21:18 UTC, sithlord48 commented on src/atcore.cpp
> +    if (!plugin()) {
this crashes.. instead use 
if (state() == DISCONNECTED || state() == CONNECTING)

2016-10-05 16:49 UTC, patrickelectric commented on src/atcore.cpp
> +    if (!plugin()) {
This is a solution, but not the beter one. The pointer was not initialized correctly, that's why the system was crashing.

2016-10-07 21:39 UTC, sithlord48 approved these changes

2016-10-07 21:41 UTC, merged