Marlin plugin
KDE/atcore pull request #24
Opened 2016-10-08 22:31 UTC by sithlord48

Create a marlin plugin 
Better detection of Firmware names by checking with less junk

2016-10-08 22:34 UTC, patrickelectric requested changes

2016-10-08 22:34 UTC, patrickelectric commented on src/atcore.cpp
> +        fwName.remove(0, 14); //remove FIRMWARE_NAME:
This form isn't robust. Maybe a combination of contains, split and other things.

2016-10-08 22:34 UTC, patrickelectric commented on src/atcore.cpp
> +        if (!fwName.toLower().contains(file.toLocal8Bit())) {
Before that, use toLower and simplifie in message and file

2016-10-08 23:04 UTC, sithlord48 commented on src/atcore.cpp
> +        if (!fwName.toLower().contains(file.toLocal8Bit())) {
:heavy_check_mark:  `fwName = fwName.toLower().simplified();`

2016-10-08 23:04 UTC, sithlord48 commented on src/atcore.cpp
> +        fwName.remove(0, 14); //remove FIRMWARE_NAME:
:heavy_check_mark: `fwName.split(':').at(1)`

2016-10-08 23:06 UTC, patrickelectric commented on src/atcore.cpp
> +        if (!fwName.toLower().contains(file.toLocal8Bit())) {
@sithlord48  and **file** variable.

2016-10-09 01:54 UTC, sithlord48 commented on src/atcore.cpp
> +        if (!fwName.toLower().contains(file.toLocal8Bit())) {
:heavy_check_mark:  `file = file.toLower().simplified();`

2016-10-09 03:22 UTC, patrickelectric approved these changes
great work @sithlord48  !

2016-10-09 11:51 UTC, merged