Add Slots to atcore
KDE/atcore pull request #32
Opened 2016-10-22 02:16 UTC by sithlord48

Add some slots and signals to atcore.
change up the text client to work better with the slots

2016-10-22 14:42 UTC, patrickelectric requested changes

2016-10-22 14:42 UTC, patrickelectric commented on src/atcore.cpp
> +            if (state() != BUSY) {
Why this ?
The set state function cannot do state != newState, state = newstate ?

2016-10-22 14:42 UTC, patrickelectric commented on src/atcore.h
> +    FINISHEDPRINT //Just Finished print job
add comma in the end of this line

2016-10-22 16:11 UTC, sithlord48 commented on src/atcore.cpp
> +            if (state() != BUSY) {
I have removed that line and done as suggested and made the check part of setState

2016-10-24 00:23 UTC, patrickelectric requested changes

2016-10-24 00:23 UTC, patrickelectric commented on src/atcore.cpp
> -
Add this line back

2016-10-24 00:23 UTC, patrickelectric commented on src/atcore.cpp
>              setState(BUSY);
Remove this line.

2016-10-24 00:55 UTC, merged