Move printing to AtCore with plugin support
KDE/atcore pull request #7
Opened 2016-09-19 20:23 UTC by sithlord48

2016-09-19 23:35 UTC, patrickelectric commented on src/atcore.cpp
> +}
Space between functions

2016-09-19 23:36 UTC, patrickelectric commented on src/plugins/grblplugin.cpp
>  }
Space

2016-09-19 23:37 UTC, patrickelectric commented on src/plugins/grblplugin.cpp
> +{
Add qunused

2016-09-19 23:38 UTC, patrickelectric commented on src/plugins/repetierplugin.cpp
> +    else{
Else is not necessary

2016-09-19 23:39 UTC, patrickelectric commented on src/protocollayer.cpp
Remove this comments

2016-09-19 23:39 UTC, patrickelectric requested changes

2016-09-19 23:52 UTC, sithlord48 commented on src/protocollayer.cpp
:heavy_check_mark:

2016-09-19 23:52 UTC, sithlord48 commented on src/plugins/grblplugin.cpp
> +{
:heavy_check_mark:  Q_UNUSED(lastMessage)

2016-09-19 23:52 UTC, sithlord48 commented on src/atcore.cpp
> +}
:heavy_check_mark: 
emit( receivedMessage( lastMessage ) );

2016-09-20 00:21 UTC, sithlord48 commented on src/plugins/grblplugin.cpp
>  }
:heavy_check_mark:

2016-09-20 00:22 UTC, sithlord48 commented on src/plugins/repetierplugin.cpp
> +    else{
:heavy_check_mark:

2016-09-23 12:16 UTC, closed without merging