Printing Support moved to AtCore
KDE/atcore pull request #8
Opened 2016-09-23 12:42 UTC by sithlord48

All print functions are in AtCore now. 
Protocol Layer is removed.

2016-09-24 13:48 UTC, patrickelectric reviewed
Please, use a title and after a text block in the commit message.

2016-09-24 13:50 UTC, patrickelectric commented on src/atcore.h
> +    void newMessage(const QByteArray& msg);
Be consistent with argument name, use message.

2016-09-24 13:51 UTC, patrickelectric commented on testclient/mainwindow.cpp
> +    QStringList ports;
This is a style correction, need to be in other commit.

2016-09-24 13:51 UTC, patrickelectric commented on testclient/mainwindow.cpp
> +    QStringList ports;
But Let it in this way, I will create a astyle script later.

2016-09-24 13:53 UTC, patrickelectric requested changes

2016-09-24 20:54 UTC, sithlord48 commented on src/atcore.h
> +    void newMessage(const QByteArray& msg);
Changed argument name from msg to message

2016-09-24 23:27 UTC, patrickelectric approved these changes

2016-09-24 23:27 UTC, patrickelectric commented
You can merge it

2016-09-27 14:16 UTC, sithlord48 commented
:heavy_check_mark: merged into kde/atcore

2016-09-27 14:16 UTC, closed without merging